add japanese
uploadcare/social-l10n pull request #22
Opened 2019-03-03 10:45 UTC by heocoi

Hi,
I added a locale file for Japanese.

I'm using Uploadcare for a production web app and need to locale Social tabs.
Could you merge it soon?

Thanks.

2020-02-11 11:01 UTC, andrewshkovskii commented
@heocoi Hello.
Sorry for little bit late response .. :)
There are missing translation keys for `drive`, current keys are:

```
      myFiles: 'My Files',
      shared: 'Shared with me',
      starred: 'Starred',
      search: 'Search',
      teamDrives: 'Team drives'
```
Same for `oneDrive`: 
```
        myFiles: 'My files',
        shared: 'Shared with me',
        sharepoint: 'SharePoint',
        myDrives: 'My drives',
        groups: 'My groups'
```

And `gphotos`:

```
      myAlbums: 'Albums',
      myPhotos: 'Photos'
```

2020-02-11 11:01 UTC, andrewshkovskii requested changes
See my comment, please

2020-02-11 11:05 UTC, andrewshkovskii commented on ja.js
> +// http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html
```suggestion
// https://unicode.org/cldr/charts/34/supplemental/language_plural_rules.html
```

2024-12-04 12:21 UTC, nd0ut approved these changes

2024-12-04 12:22 UTC, merged