[SCS-128] Add `disconnect` en translation
uploadcare/social-l10n pull request #38
Opened 2022-03-18 08:11 UTC by nd0ut

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-03-25 06:19 UTC, sharov approved these changes

2022-03-31 11:17 UTC, homm requested changes

2022-03-31 11:17 UTC, homm commented on en.js
> +  disconnect: 'Disconnect from',
Discussed with @sharov 

```suggestion
  disconnect: 'Revoke access',
```

2022-03-31 12:41 UTC, homm approved these changes

2022-04-04 12:05 UTC, merged